---
title: Swivel Scheduler
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@swivelscheduler.com
description: 
url: "//swivelscheduler.com"
baseurl: "/"
twitter_username: swivelscheduler
github_username: swivelscheduler
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-gzip
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- gulpfile.js
- package.json
- package-lock.json
- scss
- README.md
- CNAME
sass:
  sass_dir: _scss
  style: compressed
main_nav:
- title: Features
  url: "#featuresSection"
  is_uppercase: true
- title: Pricing
  url: "#pricingSection'"
  is_uppercase: true
- title: Tutorials
  url: https://swivelscheduler.com/tutorials
  is_uppercase: true
- title: Log In
  url: "/"
  is_uppercase: false
- title: Sign Up
  url: "/"
  is_uppercase: false
footer_links:
- title: Terms
  url: terms.html
- title: Privacy Policy
  url: privacy-policy.html
- title: HIPPA Compliance
  url: hippa-compliance.html
