---
title: Swivel Scheduler
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@swivelscheduler.com
description: 
url: swivelscheduler.com
baseurl: "/"
twitter_username: swivelscheduler
github_username: swivelscheduler
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- gulpfile.js
- package.json
- package-lock.json
- scss
- README.md
- CNAME
